version: "3"
services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:latest
    depends_on:
      - db
    environment:
       SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonarqubedb
       SONAR_JDBC_USERNAME: sonar
       SONAR_JDBC_PASSWORD: sonar
     # - SONAR.SEARCH.JAVAADDITIONALOPTS: -Dbootstrap.system_call_filter=false
    volumes:
      - /opt/sonarCE/data:/opt/sonarqube/data
      - /opt/sonarCE/extentions:/opt/sonarqube/extensions
      - /opt/sonarCE/logs/:/opt/sonarqube/logs
      - "/srv/docker/keycloak/data/certs/keycloak.key:/etc/x509/https/tls.key"
      - "/srv/docker/keycloak/data/certs/keycloak.crt:/etc/x509/https/tls.crt"
    ports:
      - "9000:9000"
  db:
    container_name: postgresql
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqubedb
    volumes:
      - /opt/postgresqlCE/:/var/lib/postgresql
      - /opt/postgresqlCE/data:/var/lib/postgresql/data